### PR TITLE
INTG-528-payment-override-UX-improvement

### PR DESCRIPTION
**Pull request by gopipatell**

### CODE REVIEW

**Review by jwsandeman — DISMISSED** [review]
Looks Good 👍

**Review by rossi-mx51 — CHANGES_REQUESTED** [review]
Please don't merge, I need to review it.

**Review by rossi-mx51 — APPROVED** [review]
LGTM

**Comment by rossi-mx51** [comment]
@gopipatell  I'm about to merge the PR but there're 2 small conflict. Are you able to resolve it ?

**Review by rossi-mx51 — APPROVED** [review]

**Pull request merged**
